### ISSUE TITLE
SD/MMC bug

### ISSUE THREAD

**Issue by milgrau99** [jhswartz/rk3229#1]
On MXQ-Pro 4k with SD/MMC, device isn't recorgnized as a serial device, only by rockchip tools or fastboot
Compiled with latest linaro GCC (on ubuntu 18.04)

**Comment by jhswartz** [comment]
Can you elaborate on what you mean by a serial device in this context?

**Comment by milgrau99** [comment]
well, I followed the steps in the build and install process but couldn't connect to the pc via serial / uart, tried to connect using a male-male usb cable

  was only recognized with rkdeveloptool with sd card connected and loader written on it

**Comment by jhswartz** [comment]
To confirm, I assume you have attached a suitable 3.3V UART adapter from your PC to the board's GND, RX and TX UART pads and connected tried to establish a connection at 1500000 baud, 8 data bits, no parity and 1 stop bit?

In any case, the USB A (male-to-male) connection to the board for ROCKUSB isn't supported by mainline U-Boot at the moment - so you won't be able to read/write to the board that way unless you drop into MASKROM mode.

**Comment by milgrau99** [comment]
however, I didn't understand how to erase the onboard loader (the rkbin merge I followed according to the rockchip site)

**Comment by milgrau99** [comment]
I thought about this possibility (using an uart / usb adapter)
I can also call in MASKROM mode (when I connect it to the computer, it is recognized by rkdeveloptool, so I can use the command "rkdeveloptool rd 3"

**Comment by jhswartz** [comment]
Well without UART, you won't get console access - unless you get everything correct and boot into the image without any issues and view tty0 via HDMI.

With regard to the initial loader on the onboard flash (it begins at sector 0x40), it is the first option that the BOOTROM program tries to jump to. If you overwrite even just the first sector, this will cause BOOTROM to attempt to call a loader from an SD card instead.

**Comment by milgrau99** [comment]
To delete the loader, can I follow the same steps described in the installation via eMMC?

**Comment by jhswartz** [comment]
Yes

**Comment by milgrau99** [comment]
One more thing
How i can merge the rkbin loader?

**Comment by jhswartz** [comment]
$ git clone https://github.com/rockchip-linux/rkbin
$ cd rkbin
$ ln -s RKBOOT/RK322XATMINIALL.ini CONFIG.ini
$ tools/boot_merger
$ ls -al rk322x_loader_at_v1.08.256.bin
-rw-r--r-- 1 user user 211278 Sep 19 08:13 rk322x_loader_at_v1.08.256.bin

**Comment by milgrau99** [comment]
Thanks 😁😁
