### ISSUE TITLE
Can't compile u-boot...

### ISSUE THREAD

**Issue by RomSand** [jhswartz/rk3229#2]
Hi, I'm always getting gcc error, would it be possible to provide precompiled version od u-boot. Thanks.

**Comment by jhswartz** [comment]
Sorry, I won't provide precompiled binaries. But feel free to provide your build log and information about the system that you're crosscompiling from.

**Comment by RomSand** [comment]
System:
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-66-generic x86_64)
Error:
```
 LD      out/arm-plat-rockchip/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.elf
arm-linux-gnueabihf-ld.bfd: out/arm-plat-rockchip/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.elf: Not enough room for program headers, try linking with -N
arm-linux-gnueabihf-ld.bfd: final link failed: Bad value
ta/arch/arm/link.mk:71: recipe for target 'out/arm-plat-rockchip/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.elf' failed
make: *** [out/arm-plat-rockchip/ta/avb/023f8f1a-292a-432b-8fc4-de8471358067.elf] Error 1
```
Thanks.

**Comment by RomSand** [comment]
I know that I need to use --no-dynamic-linker but don't know where to put it...

**Comment by jhswartz** [comment]
I'll need to see more than that what you've pasted. Please attach build-optee.log

**Comment by RomSand** [comment]
Thank you.
I changed a little bit make file and could compile it now linux boots fine... but missing ethernet and wireless drivers. Did you try to make armbian to lunch ?

**Comment by jhswartz** [comment]
Those drivers will depend on the board/device that you are using. And I have not tried to boot armbian, I have no interest in distributions that use systemd. :)
