### ISSUE TITLE
Can't boot from emmc...

### ISSUE THREAD

**Issue by RomSand** [jhswartz/rk3229#3]
Hi wrote loader and u-boot to emmc and receive this from serial:
¦
@@¦ ¦¦¦DDR Version V1.06 20170902_dbg
In
300MHz
DDR3
Bus Width=16 Col=11 Bank=8 Row=15 CS=1 Die Bus-Width=16 Size=1024MB
mach:2
OUT
Boot1 Release Time: Nov  9 2017 15:32:49, version: 2.47
ChipType = 0xc, 382
SdmmcInit=2 0
BootCapSize=2000
UserCapSize=7456MB
FwPartOffset=2000 , 2000
SdmmcInit=0 20
StorageInit ok = 3611502
SecureMode = 0
hdr 0x0:0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,

hdr 0x0:0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,

hdr 0x0:0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,

hdr 0x0:0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,

hdr 0x0:0xd0,0x0d,0xfe,0xed,0x00,0x00,0x03,0x87,0x00,0x00,0x00,0x38,0x00,0x00,0x03,0x04,

Code check OK! theLoader 0x68400000, 3628285
powerOn 4305719

any ideas why ?
Thanks.

**Comment by jhswartz** [comment]
It doesn't appear that your device is executing U-Boot TPL at all. It looks like the output of the rockchip loader to me.

1. Are you sure that your device has eMMC and not NAND flash?

2. If your answer to 1 is yes, are you sure that you were in MASKROM mode when you wrote "loader.img" and "u-boot.itb" to the device?

3. If your answers to both 1 and 2 are yes, are you sure that you that you specified the correct initial sectors for "loader.img" and "u-boot.itb" to be written to?

**Comment by RomSand** [comment]
Hi,
1. eMMC 
2. Yes MASKROM
3. sectors 40 and 4000 images are same I used for SD Card. 
I'll check maybe removed emmc when compiled u-boot. but when I boot from SD it sees it...

**Comment by jhswartz** [comment]
According to the log that you shared, your device is still booting what is likely to be the original loader shipped with your device. In other words you have not overwritten the initial loader. :)
