### ISSUE TITLE
Linux Kernel Ethernet support.

### ISSUE THREAD

**Issue by RomSand** [jhswartz/rk3229#4]
As I understood ethernet is part of 3229 SOC so the kernel need to be patched to support it ?
I don't see it in dmesg can you please point how can I set it up.

Thank you.

**Comment by jhswartz** [comment]
That shouldn't be necessary.

If you followed the compilation guide a patch should have been applied to create "arch/arm/boot/dts/rk3229-xms6.dts" in the linux source directory. This device tree definition contains a "gmac" node which provides the configuration necessary to enable the ethernet PHY. 

If all is well, you should expect to see kernel messages from rk_gmac-dwmac to the effect of:
[    0.587893] rk_gmac-dwmac 30200000.ethernet: PTP uses main clock
[    0.588856] rk_gmac-dwmac 30200000.ethernet: clock input or output? (output).
[    0.589734] rk_gmac-dwmac 30200000.ethernet: Can not read property: tx_delay.
[    0.590591] rk_gmac-dwmac 30200000.ethernet: set tx_delay to 0x30
[    0.591328] rk_gmac-dwmac 30200000.ethernet: Can not read property: rx_delay.
[    0.592184] rk_gmac-dwmac 30200000.ethernet: set rx_delay to 0x10
[    0.592931] rk_gmac-dwmac 30200000.ethernet: integrated PHY? (yes).
[    0.594009] rk_gmac-dwmac 30200000.ethernet: cannot get clock clk_mac_speed
[    0.600613] rk_gmac-dwmac 30200000.ethernet: init for RMII
[    0.643468] rk_gmac-dwmac 30200000.ethernet: User ID: 0x10, Synopsys ID: 0x35
[    0.644392] rk_gmac-dwmac 30200000.ethernet: 	DWMAC1000
[    0.645038] rk_gmac-dwmac 30200000.ethernet: DMA HW capability register supported
[    0.645937] rk_gmac-dwmac 30200000.ethernet: RX Checksum Offload Engine supported
[    0.646834] rk_gmac-dwmac 30200000.ethernet: COE Type 2
[    0.647469] rk_gmac-dwmac 30200000.ethernet: TX Checksum insertion supported
[    0.648308] rk_gmac-dwmac 30200000.ethernet: Wake-Up On Lan supported
[    0.649145] rk_gmac-dwmac 30200000.ethernet: Normal descriptors
[    0.649862] rk_gmac-dwmac 30200000.ethernet: Ring mode enabled
[    0.650565] rk_gmac-dwmac 30200000.ethernet: Enable RX Mitigation via HW Watchdog Timer
[    0.651544] rk_gmac-dwmac 30200000.ethernet (unnamed net_device) (uninitialized): device MAC address 5e:c6:77:59:d5:e1

You should find that an ethernet interface, likely to be "eth0", is available.

What device/board are you using? Feel free to drop your kernel messages log here.

**Comment by RomSand** [comment]
Board is R329Q_V3.1 
Boot Log:
`

U-Boot 2019.07-rc4-dirty (Nov 08 2019 - 11:33:46 -0800)

Model: Rockchip RK3229 Evaluation board
DRAM:  1022 MiB
MMC:   dwmmc@30000000: 1, dwmmc@30020000: 0
Loading Environment from MMC... *** Warning - bad CRC, using default environment

In:    serial@11030000
Out:   serial@11030000
Err:   serial@11030000
Model: Rockchip RK3229 Evaluation board
rockchip_dnl_key_pressed: adc_channel_single_shot fail!
Net:
Warning: ethernet@30200000 (eth0) using random MAC address - 82:e1:64:ab:26:c4
eth0: ethernet@30200000
Hit any key to stop autoboot:  0
switch to partitions #0, OK
mmc0(part 0) is current device
** No partition table - mmc 0 **
switch to partitions #0, OK
mmc1 is current device
Scanning mmc 1:4...
Found /extlinux/extlinux.conf
Retrieving file: /extlinux/extlinux.conf
229 bytes read in 1 ms (223.6 KiB/s)
1:      default
Retrieving file: /zImage
5529024 bytes read in 255 ms (20.7 MiB/s)
append: console=ttyS2,1500000n8 console=tty0 video=HDMI-A-1:1920x1080@60 ignore_loglevel debug rw root=/dev/mmcblk0p5 rootfstype=ext2 rootwait
Retrieving file: /dtb/rk3229-xms6.dtb
23569 bytes read in 6 ms (3.7 MiB/s)
## Flattened Device Tree blob at 61f00000
   Booting using the fdt blob at 0x61f00000
   Loading Device Tree to 683f7000, end 683ffc10 ... OK

Starting kernel ...

D/TC:0   psci_cpu_on:259 core_id: 1
D/TC:1   init_secondary_helper:1133 Secondary CPU Switching to normal world boot
D/TC:0   psci_cpu_on:259 core_id: 2
D/TC:2   init_secondary_helper:1133 Secondary CPU Switching to normal world boot
D/TC:0   psci_cpu_on:259 core_id: 3
D/TC:3   init_secondary_helper:1133 Secondary CPU Switching to normal world boot
[    0.000000] Booting Linux on physical CPU 0xf00
[    0.000000] Linux version 5.4.0-rc6-dirty (root@ubuntu) (gcc version 7.4.0 (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1)) #1 SMP Thu Nov 7 07:19:30 PST 2019
[    0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c5387d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Mecer Xtreme Mini S6
[    0.000000] printk: debug: ignoring loglevel setting.
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 64 MiB at 0x9c000000
[    0.000000] On node 0 totalpages: 261632
[    0.000000]   Normal zone: 1536 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 196096 pages, LIFO batch:63
[    0.000000]   HighMem zone: 65536 pages, LIFO batch:15
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.0 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.0
[    0.000000] percpu: Embedded 19 pages/cpu s47820 r8192 d21812 u77824
[    0.000000] pcpu-alloc: s47820 r8192 d21812 u77824 alloc=19*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 260096
[    0.000000] Kernel command line: console=ttyS2,1500000n8 console=tty0 video=HDMI-A-1:1920x1080@60 ignore_loglevel debug rw root=/dev/mmcblk0p5 rootfstype=ext2 rootwait
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 958456K/1046528K available (8192K kernel88K rodata, 1024K init, 282K bss, 22536K reserved, 65536K cma-re[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4    0.000000] rcu: Hierarchical RCU implementation.
[    0.0000:    RCU event tracing is enabled.
[    0.000000] rcu:     RCU restrrom NR_CPUS=16 to nr_cpu_ids=4.
[    0.000000] rcu: RCU calcula value of scheduler-enlistment delay is 10 jiffies.
[    0.0000sting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.00006, nr_irqs: 16, preallocated irqs: 16
[    0.000000] random: geandom_bytes called from start_kernel+0x314/0x4ac with crng_init=000] arch_timer: cp15 timer(s) running at 24.00MHz (phys).
[   0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff  max_idle_ns: 440795202592 ns
[    0.000008] sched_clock: 56 bi4MHz, resolution 41ns, wraps every 4398046511097ns
[    0.000023] Switching to timer-based delay loop, resolution 41ns
[    0.onsole: colour dummy device 80x30
[    0.001486] printk: consolenabled
[    0.001549] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=240000)
 pid_max: default: 32768 minimum: 301
[    0.001772] Mount-cachsh table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.00ntpoint-cache hash table entries: 2048 (order: 1, 8192 bytes, li   0.001929] *** VALIDATE tmpfs ***
[    0.002644] *** VALIDATE*
[    0.002826] *** VALIDATE cgroup1 ***
[    0.002853] *** V cgroup2 ***
[    0.002876] CPU: Testing write buffer coherency0] /cpus/cpu@f00 missing clock-frequency property
[    0.003427s/cpu@f01 missing clock-frequency property
[    0.003456] /cpusng clock-frequency property
[    0.003485] /cpus/cpu@f03 missink-frequency property
[    0.003509] CPU0: thread -1, cpu 0, soc 80000f00
[    0.004251] Setting up static identity map for 0x60 - 0x60100060
[    0.004456] rcu: Hierarchical SRCU implementa[    0.008066] smp: Bringing up secondary CPUs ...
[    0.01079d -1, cpu 1, socket 15, mpidr 80000f01
[    0.013582] CPU2: thread -1, cpu 2, socket 15, mpidr 80000f02
[    0.016245] CPU3: td -1, cpu 3, socket 15, mpidr 80000f03
[    0.016391] smp: Brou1 node, 4 CPUs
[    0.016470] SMP: Total of 4 processors activa92.00 BogoMIPS).
[    0.016487] CPU: All CPU(s) started in SVC [    0.017386] devtmpfs: initialized
[    0.023911] VFP support.3: implementor 41 architecture 2 part 30 variant 7 rev 5
[    24] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xfffffff9112604462750000 ns
[    0.024382] futex hash table entries: 10r: 4, 65536 bytes, linear)
[    0.027181] pinctrl core: initialubsystem
[    0.028785] NET: Registered protocol family 16
[  031075] DMA: preallocated 256 KiB pool for atomic coherent alloc[    0.033196] cpuidle: using governor menu
[    0.033730] hw-bakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint regis.033763] hw-breakpoint: maximum watchpoint size is 8 bytes.
[  23] Serial: AMBA PL011 UART driver
[    0.068230] vcc_sys: supp
[    0.068669] vccio_1v8: supplied by vcc_sys
[    0.068947] t: supplied by vcc_sys
[    0.069187] vccio_3v3: supplied by vc[    0.069423] vcc_phy: supplied by vccio_1v8
[    0.069777] io domain type: Translated
[    0.071380] SCSI subsystem initial[    0.071723] usbcore: registered new interface driver usbfs
[ usbcore: registered new interface driver hub
[    0.071947] usred new device driver usb
[    0.072212] pps_core: LinuxPPS API1 registered
[    0.072234] pps_core: Software ver. 5.3.6 - Cop2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.072300] E.0
[    0.074954] clocksource: Switched to clocksource arch_sys  0.124657] *** VALIDATE ramfs ***
[    0.135948] thermal_sys: ered thermal governor 'step_wise'
[    0.136593] NET: Registerecol family 2
[    0.137533] tcp_listen_portaddr_hash hash tableentries: 512 (order: 0, 6144 bytes, linear)
[    0.137600] TCP ed hash table entries: 8192 (order: 3, 32768 bytes, linear)
[  7715] TCP bind hash table entries: 8192 (order: 4, 65536 bytes,  0.137868] TCP: Hash tables configured (established 8192 bind 81    0.138070] UDP hash table entries: 512 (order: 2, 16384 bytes    0.138161] UDP-Lite hash table entries: 512 (order: 2, 16384 [    0.138470] NET: Registered protocol family 1
[    0.138536] PCI: CLS 0 bytes, default 64
[    0.139809] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 5 counters available
[   141890] Initialise system trusted keyrings
[    0.142256] workiamp_bits=30 max_order=18 bucket_order=0
[    0.149997] squashfson 4.0 (2009/01/31) Phillip Lougher
[    0.150258] ntfs: driver R/O].
[    0.151012] Key type asymmetric registered
[    0.151044] Asymmetric key parser 'x509' registered
[    0.151152] boze: 64 pages
[    0.151228] Block layer SCSI generic (bsg) drivversion 0.4 loaded (major 247)
[    0.151256] io scheduler mq-dred
[    0.151273] io scheduler kyber registered
[    0.152691i-phy 12030000.hdmi-phy: IRQ index 0 not found
[    0.159277] pator: supplied by vcc_sys
[    0.159902] pwm-regulator: suppliecc_sys
[    0.229054] Serial: 8250/16550 driver, 4 ports, IRQ s enabled
[    0.232167] printk: console [ttyS2] disabled
[    0.232296] 11030000.serial: ttyS2 at MMIO 0x11030000 (irq = 28, b0) is a 16550A
[    0.293681] printk: console [ttyS2] enabled
[    0.296069] rockchip-vop 20050000.vop: Adding to iommu group 0
[    0.300052] rockchip-drm display-subsystem: bound 20050000.vop (ops 0xc0953240)
[    0.300996] dwhdmi-rockchip 200a0000.hdmi: Detected HDMI TX controller v2.01a with HDCP (inno_dw_hdmi_phy2)
[    0.302558] dwhdmi-rockchip 200a0000.hdmi: registered DesignWare HDMI I2C bus driver
[    0.303627] rockchip-drm display-subsystem: bound 200a0000.hdmi (ops 0xc0956354)
[    0.304302] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[    0.304893] [drm] No driver support for vblank timestamp query.
[    0.305547] [drm] Cannot find any crtc or sizes
[    0.306699] [drm] Initialized rockchip 1.0.0 20140818 for display-subsystem on minor 0
[    0.309281] lima 20000000.gpu: IRQ pmu not found
[    0.309918] lima 20000000.gpu: IRQ ppmmu2 not found
[    0.310371] lima 20000000.gpu: IRQ ppmmu3 not found
[    0.310832] lima 20000000.gpu: gp - mali400 version major 1 minor 1
[    0.311452] lima 20000000.gpu: pp0 - mali400 version major 1 minor 1
[    0.312079] lima 20000000.gpu: pp1 - mali400 version major 1 minor 1
[    0.312664] lima 20000000.gpu: IRQ pp2 not found
[    0.313086] lima 20000000.gpu: IRQ pp3 not found
[    0.313510] lima 20000000.gpu: l2 cache 64K, 4-way, 64byte cache line, 64bit external bus
[    0.315037] lima 20000000.gpu: bus rate = 297000000
[    0.315501] lima 20000000.gpu: mod rate = 297000000
[    0.316472] [drm] Initialized lima 1.0.0 20190217 for 20000000.gpu on minor 1
[    0.330347] brd: module loaded
[    0.343958] loop: module loaded
[    0.345890] libphy: Fixed MDIO Bus: probed
[    0.346944] rk_gmac-dwmac 30200000.ethernet: IRQ eth_wake_irq not found
[    0.347555] rk_gmac-dwmac 30200000.ethernet: IRQ eth_lpi not found
[    0.348259] rk_gmac-dwmac 30200000.ethernet: PTP uses main clock
[    0.348928] rk_gmac-dwmac 30200000.ethernet: clock input or output? (output).
[    0.349574] rk_gmac-dwmac 30200000.ethernet: Can not read property: tx_delay.
[    0.350213] rk_gmac-dwmac 30200000.ethernet: set tx_delay to 0x30
[    0.350762] rk_gmac-dwmac 30200000.ethernet: Can not read property: rx_delay.
[    0.351400] rk_gmac-dwmac 30200000.ethernet: set rx_delay to 0x10
[    0.351962] rk_gmac-dwmac 30200000.ethernet: integrated PHY? (yes).
[    0.352615] rk_gmac-dwmac 30200000.ethernet: cannot get clock clk_mac_speed
[    0.359026] rk_gmac-dwmac 30200000.ethernet: init for RMII
[    0.405259] rk_gmac-dwmac 30200000.ethernet: User ID: 0x10, Synopsys ID: 0x35
[    0.405926] rk_gmac-dwmac 30200000.ethernet:         DWMAC1000
[    0.406403] rk_gmac-dwmac 30200000.ethernet: DMA HW capability register supported
[    0.407077] rk_gmac-dwmac 30200000.ethernet: RX Checksum Offload Engine supported
[    0.407749] rk_gmac-dwmac 30200000.ethernet: COE Type 2
[    0.408220] rk_gmac-dwmac 30200000.ethernet: TX Checksum insertion supported
[    0.408851] rk_gmac-dwmac 30200000.ethernet: Wake-Up On Lan supported
[    0.409478] rk_gmac-dwmac 30200000.ethernet: Normal descriptors
[    0.410010] rk_gmac-dwmac 30200000.ethernet: Ring mode enabled
[    0.410536] rk_gmac-dwmac 30200000.ethernet: Enable RX Mitigation via HW Watchdog Timer
[    0.411266] rk_gmac-dwmac 30200000.ethernet: device MAC address fa:35:20:46:58:40
[    0.412213] libphy: stmmac: probed
[    0.414757] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    0.415462] ehci-pci: EHCI PCI platform driver
[    0.415953] ehci-platform: EHCI generic platform driver
[    0.418876] ehci-platform 30080000.usb: EHCI Host Controller
[    0.419445] ehci-platform 30080000.usb: new USB bus registered, assigned bus number 1
[    0.420566] ehci-platform 30080000.usb: irq 39, io mem 0x30080000
[    0.444957] ehci-platform 30080000.usb: USB 2.0 started, EHCI 1.00
[    0.446715] hub 1-0:1.0: USB hub found
[    0.447155] hub 1-0:1.0: 1 port detected
[    0.450400] ehci-platform 300c0000.usb: EHCI Host Controller
[    0.450962] ehci-platform 300c0000.usb: new USB bus registered, assigned bus number 2
[    0.451979] ehci-platform 300c0000.usb: irq 41, io mem 0x300c0000
[    0.474967] ehci-platform 300c0000.usb: USB 2.0 started, EHCI 1.00
[    0.476677] hub 2-0:1.0: USB hub found
[    0.477096] hub 2-0:1.0: 1 port detected
[    0.480321] ehci-platform 30100000.usb: EHCI Host Controller
[    0.480885] ehci-platform 30100000.usb: new USB bus registered, assigned bus number 3
[    0.481901] ehci-platform 30100000.usb: irq 43, io mem 0x30100000
[    0.504955] ehci-platform 30100000.usb: USB 2.0 started, EHCI 1.00
[    0.506612] hub 3-0:1.0: USB hub found
[    0.507032] hub 3-0:1.0: 1 port detected
[    0.508026] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    0.508621] ohci-platform: OHCI generic platform driver
[    0.509472] ohci-platform 300a0000.usb: Generic Platform OHCI controller
[    0.510129] ohci-platform 300a0000.usb: new USB bus registered, assigned bus number 4
[    0.511096] ohci-platform 300a0000.usb: irq 40, io mem 0x300a0000
[    0.580025] hub 4-0:1.0: USB hub found
[    0.580448] hub 4-0:1.0: 1 port detected
[    0.581616] ohci-platform 300e0000.usb: Generic Platform OHCI controller
[    0.582262] ohci-platform 300e0000.usb: new USB bus registered, assigned bus number 5
[    0.583213] ohci-platform 300e0000.usb: irq 42, io mem 0x300e0000
[    0.649984] hub 5-0:1.0: USB hub found
[    0.650409] hub 5-0:1.0: 1 port detected
[    0.651545] ohci-platform 30120000.usb: Generic Platform OHCI controller
[    0.652190] ohci-platform 30120000.usb: new USB bus registered, assigned bus number 6
[    0.653175] ohci-platform 30120000.usb: irq 44, io mem 0x30120000
[    0.719993] hub 6-0:1.0: USB hub found
[    0.720420] hub 6-0:1.0: 1 port detected
[    0.722031] usbcore: registered new interface driver usb-storage
[    0.722989] i2c /dev entries driver
[    0.726058] rockchip-thermal 11150000.tsadc: Missing tshut-polarity property, using default (low)
[    0.726890] rockchip-thermal 11150000.tsadc: Missing rockchip,grf property
[    0.728700] softdog: initialized. soft_noboot=0 soft_margin=60 sec soft_panic=0 (nowayout=0)
[    0.729848] Synopsys Designware Multimedia Card Interface Driver
[    0.731110] dwmmc_rockchip 30000000.dwmmc: IDMAC supports 32-bit address mode.
[    0.731888] dwmmc_rockchip 30000000.dwmmc: Using internal DMA controller.
[    0.732511] dwmmc_rockchip 30000000.dwmmc: Version ID is 270a
[    0.733111] dwmmc_rockchip 30000000.dwmmc: DW MMC controller at irq 36,32 bit host data width,256 deep fifo
[    0.745124] mmc_host mmc0: Bus speed (slot 0) = 400000Hz (slot req 400000Hz, actual 400000HZ div = 0)
[    0.759446] dwmmc_rockchip 30020000.dwmmc: IDMAC supports 32-bit address mode.
[    0.760315] dwmmc_rockchip 30020000.dwmmc: Using internal DMA controller.
[    0.760954] dwmmc_rockchip 30020000.dwmmc: Version ID is 270a
[    0.761550] dwmmc_rockchip 30020000.dwmmc: DW MMC controller at irq 37,32 bit host data width,256 deep fifo
[    0.762568] mmc_host mmc1: card is non-removable.
[    0.773740] mmc_host mmc1: Bus speed (slot 0) = 1160156Hz (slot req 400000Hz, actual 290039HZ div = 2)
[    0.788390] ledtrig-cpu: registered to indicate activity on CPUs
[    0.789258] usbcore: registered new interface driver usbhid
[    0.789783] usbhid: USB HID core driver
[    0.790674] ashmem: initialized
[    0.793546] NET: Registered protocol family 10
[    0.795530] Segment Routing with IPv6
[    0.795978] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    0.797386] NET: Registered protocol family 17
[    0.798019] Key type dns_resolver registered
[    0.798612] ThumbEE CPU extension supported.
[    0.799011] Registering SWP/SWPB emulation handler
[    0.799970] Loading compiled-in X.509 certificates
[    0.822403] hctosys: unable to open rtc device (rtc0)
[    0.824001] Waiting for root device /dev/mmcblk0p5...
[    0.827691] mmc_host mmc0: Bus speed (slot 0) = 25000000Hz (slot req 25000000Hz, actual 25000000HZ div = 0)
[    0.828617] mmc0: new SDHC card at address 1234
[    0.830276] mmcblk0: mmc0:1234 SA08G 7.29 GiB
[    0.853978]  mmcblk0: p1 p2 p3 p4 p5
[    0.877665] EXT4-fs (mmcblk0p5): mounting ext2 file system using the ext4 subsystem
[    0.925219] mmc_host mmc1: Bus speed (slot 0) = 37125000Hz (slot req 37500000Hz, actual 37125000HZ div = 0)
[    0.927929] mmc1: new high speed MMC card at address 0001
[    0.928974] EXT4-fs (mmcblk0p5): warning: mounting unchecked fs, running e2fsck is recommended
[    0.930570] mmcblk1: mmc1:0001 H8G2d 7.28 GiB
[    0.931710] mmcblk1boot0: mmc1:0001 H8G2d partition 1 4.00 MiB
[    0.932939] mmcblk1boot1: mmc1:0001 H8G2d partition 2 4.00 MiB
[    0.934108] mmcblk1rpmb: mmc1:0001 H8G2d partition 3 4.00 MiB, chardev (246:0)
[    1.355070] [drm] Cannot find any crtc or sizes
[    1.727557] random: fast init done
[    1.732291] EXT4-fs (mmcblk0p5): mounted filesystem without journal. Opts: (null)
[    1.733087] VFS: Mounted root (ext2 filesystem) on device 179:5.
[    1.781611] devtmpfs: mounted
[    1.783280] Freeing unused kernel memory: 1024K
[    1.783936] Run /sbin/init as init process
[    4.444091] udevd[205]: starting version 3.2.2
[    4.562696] random: udevd: uninitialized urandom read (16 bytes read)
[    4.569004] random: udevd: uninitialized urandom read (16 bytes read)
[    4.569725] random: udevd: uninitialized urandom read (16 bytes read)
[    4.719523] udevd[206]: starting eudev-3.2.2
[    7.647141] EXT4-fs (mmcblk0p5): re-mounted. Opts: (null)
[   10.155137] urandom_read: 2 callbacks suppressed
[   10.155156] random: dd: uninitialized urandom read (512 bytes read)
[   12.123685] ttyS2 - failed to request DMA

android login:

`

**Comment by jhswartz** [comment]
I didn't have that problem. Check your APT configuration.

PS: If you're going to log issues, please specify upfront if, and how, you've deviated from the guide.
