### ISSUE TITLE
Wifi detection.

### ISSUE THREAD

**Issue by RomSand** [jhswartz/rk3229#6]
I would like to know how can I get wifi working I can't find it in dmesg not in lspci or lsusb, can you please give couple of tips to start with. Thank you.

**Comment by RomSand** [comment]
I checked my chip is SV6051P I think I can use sourcer from here https://github.com/trustfarm/orangepi-zero-tfarm/tree/master/OrangePi-Kernel/linux-3.4/drivers/net/wireless/ssv6xxx but how to add them to kernel ?

**Comment by jhswartz** [comment]
First find out if the mainline contains a suitable driver for that chip.  In any case you will also want to get as much technical reference information about it as possible, for example: a datasheet, technical reference manual, and application notes.

**Comment by RomSand** [comment]
Mainline doesn't have it, drivers compiles succesfully only on kernel 3.4. 
on 5 I get 
 error: implicit declaration of function ‘get_ds’; did you mean ‘get_fs’?

**Comment by jhswartz** [comment]
Are you comfortable with C programming? Some of the interfaces have changed between 3.x and 5.x kernel branches, but I'm sure with a bit of effort it could be brought up. Was the driver available in mainline 3.4? Or just in a branch associated with the OrangePi?

**Comment by RomSand** [comment]
It never been in mainline only branch, android with 4.10 kernel has this driver, but no sources. My C programming not so good limited to embedded systems... If I wouldn't find any sourcer for 4 kernel  with it, will switch to usb wifi...

**Comment by jhswartz** [comment]
Switching to USB wifi will probably be the easiest solution for the time being. I have an MXQ-4k box that I think has the same radio chip - maybe I'll attempt getting the driver to work in current mainline version sometime.
