### ISSUE TITLE
U-boot SPL mmc error

### ISSUE THREAD

**Issue by jmcastillejo** [jhswartz/rk3229#7]
I have compiled u-boot following the loading instructions on the memory card, I get the following error:

U-Boot SPL 2020.01-dirty (Jul 14 2020 - 21:14:31 +0200)
Trying to boot from MMC1
Card did not respond to voltage select!
spl: mmc init failed with error: -95
SPL: failed to boot from all boot devices
### ERROR ### Please RESET the board ###

it is a tv box rk3229 with 2Gb of ram and 8gb NAND Flash

**Comment by jhswartz** [comment]
Unfortunately, this will not work for devices that have onboard NAND flash instead of an eMMC, as neither mainline U-Boot nor mainline Linux have support for the Rockchip NAND controller.
